blank_issues_enabled: true
contact_links:
  - name: 🛠 Submit a pull request
    url: https://github.com/CHCAA-EDUX/scientific-computing-01/pulls
    about: Did you spot a mistake and know how to fix it? Feel free to submit a PR and contribute!
